let myjocks = [
  {
    category: "Pun",
    type: "single",
    joke: 'Today, my son asked "Can I have a book mark?" and I burst into tears.\n11 years old and he still doesn\'t know my name is Brian.',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 200,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: 'I have these weird muscle spasms in my gluteus maximus.\nI figured out from my doctor that everything was alright:\nHe said "Weird flex, butt okay."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 82,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "I have a joke about Stack Overflow, but you would say it's a duplicate.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 301,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your momma is so fat, you need to switch to NTFS to store a picture of her.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 55,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 38,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: 'Two fish in a tank. One turns to the other and says, "Do you know how to drive this thing?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 185,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Yo mama is so old, she knew Burger King while he was still a prince.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 306,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "I visited my friend at his new house. He told me to make myself at home. So I threw him out. I hate having visitors.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 304,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: '"Honey, go to the store and buy some eggs."\n"OK."\n"Oh and while you\'re there, get some milk."\nHe never returned.',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 18,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "I have a fish that can breakdance! Only for 20 seconds though, and only once.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 237,
    safe: false,
    lang: "en",
  },
];
let index = Math.floor(Math.random() * (myjocks.length - 1));
jocks.innerHTML = myjocks[index].jocks;
